/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cpn: typeof import('./components/cpn/src/cpn.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Placeholder: typeof import('./shared-cpn/placeholder/src/placeholder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
